version: "3"

services:
  web:
    build: .
    restart: always
    links:
      - db
      - redis
      - es
    expose:
      - 3000
    container_name: "misskey_web"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/misskey/files

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:11.2-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
    networks:
      - internal_network
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  external_network:
    external: true
